# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4a49425008d67ddfc1c60ce32545dedc2c8f70d169739c040e795a262462b98a631fc912cd8e17418057642b07e78bf59625ea1bcd73f45c1d3a1cd8b6b19526

test:
  secret_key_base: 9acab9ce9fe97d348f7d700fe74248fdf52b0e95413253f554b74616d3ddc195a3cefb3c4d5a46d58cad9c304191f420a824fef6dc243f08251761400f220a54

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
